import type { Donor } from '../../types';

export function transformDonorFromDB(dbDonor: any): Donor {
  return {
    id: dbDonor.id,
    'First Name': dbDonor['First Name'],
    'Middle Name': dbDonor['Middle Name'],
    'Last Name': dbDonor['Last Name'],
    'DS Rating': dbDonor['DS Rating'],
    'Quality Score': dbDonor['Quality Score'],
    'Profile': dbDonor['Profile'],
    'RFM Total': dbDonor['RFM Total'],
    'Last Gift Date': dbDonor['Last Gift Date'],
    'Total Gift Amount': dbDonor['Total Gift Amount'],
    '# Of Gifts': dbDonor['# Of Gifts'],
    'Age': dbDonor['Age'],
    'Date Of Birth': dbDonor['Date Of Birth'],
    'Phone Number': dbDonor['Phone Number'],
    'Address': dbDonor['Address'],
    'Address 2': dbDonor['Address 2'],
    'City': dbDonor['City'],
    'State': dbDonor['State'],
    'Zip': dbDonor['Zip'],
    'Client ID': dbDonor['Client ID'],
    'SP-First': dbDonor['SP-First'],
    'SP-Middle': dbDonor['SP-Middle'],
    'SP-Last': dbDonor['SP-Last'],
    'Notes': dbDonor['Notes'],
    'Largest Gift Amount': dbDonor['Largest Gift Amount'],
    'Largest Gift Date': dbDonor['Largest Gift Date'],
    'Last Gift Amount': dbDonor['Last Gift Amount'],
    'First Date Range': dbDonor['First Date Range'],
    'First Gift Amount': dbDonor['First Gift Amount'],
    'Total Of Likely Matches': dbDonor['Total Of Likely Matches'],
    '# Of Gift Matches': dbDonor['# Of Gift Matches'],
    'Foundation': dbDonor['Foundation'],
    'Fnd Assets': dbDonor['Fnd Assets'],
    'NonProfit': dbDonor['NonProfit'],
    'Political Likely Count': dbDonor['Political Likely Count'],
    'Political Likely Total': dbDonor['Political Likely Total'],
    'Maybe Total': dbDonor['Maybe Total'],
    'Largest Gift Found': dbDonor['Largest Gift Found'],
    'Largest Gift Found Lower Range': dbDonor['Largest Gift Found Lower Range'],
    'Wealth-Based Capacity': dbDonor['Wealth-Based Capacity'],
    'Real Estate Est': dbDonor['Real Estate Est'],
    '# Of Prop': dbDonor['# Of Prop'],
    'Real Estate Trust': dbDonor['Real Estate Trust'],
    '# of ST w/Prop': dbDonor['# of ST w/Prop'],
    'Zestimate Total': dbDonor['Zestimate Total'],
    'Zestimate Count': dbDonor['Zestimate Count'],
    'LN Total': dbDonor['LN Total'],
    'LN Count': dbDonor['LN Count'],
    'SEC Stock Value': dbDonor['SEC Stock Value'],
    'SEC Stock or Insider': dbDonor['SEC Stock or Insider'],
    'Market Guide': dbDonor['Market Guide'],
    'Market Guide Comp': dbDonor['Market Guide Comp'],
    'Market Guide Options': dbDonor['Market Guide Options'],
    'Business Revenue': dbDonor['Business Revenue'],
    'Business Affiliation': dbDonor['Business Affiliation'],
    'Pension Admin': dbDonor['Pension Admin'],
    'Pension Assets': dbDonor['Pension Assets'],
    'Estimated Capacity': dbDonor['Estimated Capacity'],
    'Annual Fund Likelihood': dbDonor['Annual Fund Likelihood'],
    'Major Gift Likelihood': dbDonor['Major Gift Likelihood'],
    'PGID': dbDonor['PGID'],
    'Vip Match': dbDonor['Vip Match'],
    'Inner Circle': dbDonor['Inner Circle'],
    'Average Home Value': dbDonor['Average Home Value'],
    'Median Household Income': dbDonor['Median Household Income'],
    'Corp Tech': dbDonor['Corp Tech'],
    'FAA Pilots': dbDonor['FAA Pilots'],
    'Airplane Owner': dbDonor['Airplane Owner'],
    'Boat Owner': dbDonor['Boat Owner'],
    'Whos Who': dbDonor['Whos Who'],
    'RFM Recent Gift': dbDonor['RFM Recent Gift'],
    'RFM Freq': dbDonor['RFM Freq'],
    'RFM Money': dbDonor['RFM Money'],
    'Classic Quality Score': dbDonor['Classic Quality Score'],
    'Prefix': dbDonor['Prefix'],
    'Suffix': dbDonor['Suffix'],
    'Higher Education Count': dbDonor['Higher Education Count'],
    'Higher Education Total': dbDonor['Higher Education Total'],
    'Education Gift Count': dbDonor['Education Gift Count'],
    'Education Gift Amount': dbDonor['Education Gift Amount'],
    'Philanthropy and Grantmaking Count': dbDonor['Philanthropy and Grantmaking Count'],
    'Philanthropy and Grantmaking Total': dbDonor['Philanthropy and Grantmaking Total'],
    'Healthcare Count': dbDonor['Healthcare Count'],
    'Healthcare Total': dbDonor['Healthcare Total'],
    'Arts Gift Count': dbDonor['Arts Gift Count'],
    'Arts Gift Amount': dbDonor['Arts Gift Amount'],
    'Republican Gift Count': dbDonor['Republican Gift Count'],
    'Republican Gift Total': dbDonor['Republican Gift Total'],
    'Democratic Gift Count': dbDonor['Democratic Gift Count'],
    'Democratic Gift Amount': dbDonor['Democratic Gift Amount'],
    'Other Political Count': dbDonor['Other Political Count'],
    'Other Political Total': dbDonor['Other Political Total'],
    'Religion Count': dbDonor['Religion Count'],
    'Religion Total': dbDonor['Religion Total'],
    'Society Benefit Count': dbDonor['Society Benefit Count'],
    'Society Benefit Total': dbDonor['Society Benefit Total'],
    'Shale Wealth': dbDonor['Shale Wealth'],
    'MBT Net Worth': dbDonor['MBT Net Worth'],
    'MBT Income Estimate': dbDonor['MBT Income Estimate'],
    'MBT Highest Asset': dbDonor['MBT Highest Asset'],
    'User1': dbDonor['User1'],
    'User2': dbDonor['User2'],
    'User3': dbDonor['User3'],
    'User4': dbDonor['User4'],
    'User5': dbDonor['User5'],
    'User6': dbDonor['User6'],
    'User7': dbDonor['User7'],
    'User8': dbDonor['User8'],
    'User9': dbDonor['User9'],
    'User10': dbDonor['User10'],
    'User11': dbDonor['User11'],
    'User12': dbDonor['User12'],
    'User13': dbDonor['User13'],
    'User14': dbDonor['User14'],
    'User15': dbDonor['User15'],
    'User16': dbDonor['User16'],
    'User17': dbDonor['User17'],
    'User18': dbDonor['User18'],
    'User19': dbDonor['User19'],
    'User20': dbDonor['User20'],
    'Email': dbDonor['Email'],
    'Assessed': dbDonor['Assessed'],
    'Assessment Questions': dbDonor['Assessment Questions'],
    'IRS 990PF': dbDonor['IRS 990PF'],
    'IRS PUB78': dbDonor['IRS PUB78'],
    'Date Searched': dbDonor['Date Searched']
  };
}

export function transformDonorForDB(donor: Donor, userId?: string) {
  if (!userId) {
    throw new Error('User ID is required when transforming donor for database');
  }

  return {
    ...donor,
    user_id: userId,
    'Date Searched': new Date().toISOString()
  };
}