export const donors = [
  {
    "First Name": "Shanthini",
    "Middle Name": "",
    "Last Name": "Jayanthan",
    "DS Rating": "DS1-1",
    "Quality Score": 18.5,
    "Profile": "View",
    "RFM Total": 1,
    "Last Gift Date": "",
    "Total Gift Amount": "$0",
    "# Of Gifts": 0,
    "Age": 0,
    "Date Of Birth": "",
    "Phone Number": "",
    "Address": "35 Turnberry Road",
    "Address 2": "",
    "City": "Wallingford",
    "State": "CT",
    "Zip": "06492",
    "Client ID": "",
    "SP-First": "Jay",
    "SP-Middle": "K",
    "SP-Last": "Jayanthan",
    "Notes": "",
    "Largest Gift Amount": "$0",
    "Largest Gift Date": "",
    "Last Gift Amount": "$0",
    "First Date Range": "",
    "First Gift Amount": "$0",
    "Total Of Likely Matches": "$0",
    "# Of Gift Matches": 0,
    "Foundation": "No",
    "Fnd Assets": "$0",
    "NonProfit": "Maybe",
    "Political Likely Count": 55,
    "Political Likely Total": "$113,900",
    "Maybe Total": "$0",
    "Largest Gift Found": "$5,000",
    "Largest Gift Found Lower Range": "$5,000",
    "Wealth-Based Capacity": "F - $500,000 - $999,999",
    "Real Estate Est": "$1,444,285",
    "# Of Prop": 2,
    "Real Estate Trust": "No",
    "# of ST w/Prop": 2,
    "Zestimate Total": "$0",
    "Zestimate Count": 0,
    "LN Total": "$0",
    "LN Count": 0,
    "SEC Stock Value": "$0",
    "SEC Stock or Insider": "No",
    "Market Guide": "No",
    "Market Guide Comp": "$0",
    "Market Guide Options": "$0",
    "Business Revenue": "$0",
    "Business Affiliation": "Yes",
    "Pension Admin": "No",
    "Pension Assets": "$0",
    "Estimated Capacity": "$518,133",
    "Annual Fund Likelihood": 97,
    "Major Gift Likelihood": 93,
    "PGID": 7,
    "Vip Match": "No",
    "Inner Circle": 0,
    "Average Home Value": "$178,037",
    "Median Household Income": "$57,308",
    "Corp Tech": "No",
    "FAA Pilots": "No",
    "Airplane Owner": "No",
    "Boat Owner": "No",
    "Whos Who": "No",
    "RFM Recent Gift": 0,
    "RFM Freq": 0,
    "RFM Money": 0,
    "Classic Quality Score": 16.3,
    "Prefix": "",
    "Suffix": "",
    "Higher Education Count": 0,
    "Higher Education Total": "$0",
    "Education Gift Count": 0,
    "Education Gift Amount": "$0",
    "Philanthropy and Grantmaking Count": 0,
    "Philanthropy and Grantmaking Total": "$0",
    "Healthcare Count": 0,
    "Healthcare Total": "$0",
    "Arts Gift Count": 0,
    "Arts Gift Amount": "$0",
    "Republican Gift Count": 9,
    "Republican Gift Total": "$12,600",
    "Democratic Gift Count": 21,
    "Democratic Gift Total": "$19,600",
    "Other Political Count": 25,
    "Other Political Total": "$81,700",
    "Religion Count": 0,
    "Religion Total": "$0",
    "Society Benefit Count": 0,
    "Society Benefit Total": "$0",
    "Shale Wealth": 0,
    "MBT Net Worth": "",
    "MBT Income Estimate": "",
    "MBT Highest Asset": ""
  },
  {
    "First Name": "Marilyn",
    "Middle Name": "",
    "Last Name": "Allan",
    "DS Rating": "DS1-1",
    "Quality Score": 18.4,
    "Profile": "View",
    "RFM Total": 1,
    "Last Gift Date": "",
    "Total Gift Amount": "$0",
    "# Of Gifts": 0,
    "Age": 0,
    "Date Of Birth": "",
    "Phone Number": "",
    "Address": "130 Colton Road",
    "Address 2": "",
    "City": "Glastonbury",
    "State": "CT",
    "Zip": "06033",
    "Client ID": "",
    "SP-First": "Donald",
    "SP-Middle": "",
    "SP-Last": "Allan",
    "Notes": "",
    "Largest Gift Amount": "$0",
    "Largest Gift Date": "",
    "Last Gift Amount": "$0",
    "First Date Range": "",
    "First Gift Amount": "$0",
    "Total Of Likely Matches": "$1,000",
    "# Of Gift Matches": 2,
    "Foundation": "Maybe",
    "Fnd Assets": "$0",
    "NonProfit": "Maybe",
    "Political Likely Count": 34,
    "Political Likely Total": "$18,098",
    "Maybe Total": "$262,001",
    "Largest Gift Found": "$5,000",
    "Largest Gift Found Lower Range": "$5,000",
    "Wealth-Based Capacity": "H - $100,000 - $249,999",
    "Real Estate Est": "$1,540,118",
    "# Of Prop": 3,
    "Real Estate Trust": "No",
    "# of ST w/Prop": 1,
    "Zestimate Total": "$0",
    "Zestimate Count": 0,
    "LN Total": "$0",
    "LN Count": 0,
    "SEC Stock Value": "$15,323,573",
    "SEC Stock or Insider": "Maybe",
    "Market Guide": "No",
    "Market Guide Comp": "$0",
    "Market Guide Options": "$0",
    "Business Revenue": "$12,747,200,000",
    "Business Affiliation": "Maybe",
    "Pension Admin": "No",
    "Pension Assets": "$0",
    "Estimated Capacity": "$242,434",
    "Annual Fund Likelihood": 242,
    "Major Gift Likelihood": 158,
    "PGID": 7,
    "Vip Match": "No",
    "Inner Circle": 0,
    "Average Home Value": "$244,258",
    "Median Household Income": "$77,991",
    "Corp Tech": "No",
    "FAA Pilots": "Maybe",
    "Airplane Owner": "No",
    "Boat Owner": "No",
    "Whos Who": "No",
    "RFM Recent Gift": 0,
    "RFM Freq": 0,
    "RFM Money": 0,
    "Classic Quality Score": 15.2,
    "Prefix": "",
    "Suffix": "",
    "Higher Education Count": 0,
    "Higher Education Total": "$0",
    "Education Gift Count": 0,
    "Education Gift Amount": "$0",
    "Philanthropy and Grantmaking Count": 0,
    "Philanthropy and Grantmaking Total": "$0",
    "Healthcare Count": 0,
    "Healthcare Total": "$0",
    "Arts Gift Count": 1,
    "Arts Gift Amount": "$1,000",
    "Republican Gift Count": 0,
    "Republican Gift Total": "$0",
    "Democratic Gift Count": 7,
    "Democratic Gift Total": "$1,330",
    "Other Political Count": 27,
    "Other Political Total": "$16,768",
    "Religion Count": 0,
    "Religion Total": "$0",
    "Society Benefit Count": 0,
    "Society Benefit Total": "$0",
    "Shale Wealth": 0,
    "MBT Net Worth": "",
    "MBT Income Estimate": "",
    "MBT Highest Asset": ""
  }
];