export interface Donor {
  id?: string;
  'First Name': string;
  'Middle Name': string;
  'Last Name': string;
  'DS Rating': string;
  'Quality Score': number;
  'Profile': string;
  'RFM Total': number;
  'Last Gift Date': string;
  'Total Gift Amount': string;
  '# Of Gifts': number;
  'Age': number;
  'Date Of Birth': string;
  'Phone Number': string;
  'Address': string;
  'Address 2': string;
  'City': string;
  'State': string;
  'Zip': string;
  'Client ID': string;
  'SP-First': string;
  'SP-Middle': string;
  'SP-Last': string;
  'Notes': string;
  'Largest Gift Amount': string;
  'Largest Gift Date': string;
  'Last Gift Amount': string;
  'First Date Range': string;
  'First Gift Amount': string;
  'Total Of Likely Matches': string;
  '# Of Gift Matches': number;
  'Foundation': string;
  'Fnd Assets': string;
  'NonProfit': string;
  'Political Likely Count': number;
  'Political Likely Total': string;
  'Maybe Total': string;
  'Largest Gift Found': string;
  'Largest Gift Found Lower Range': string;
  'Wealth-Based Capacity': string;
  'Real Estate Est': string;
  '# Of Prop': number;
  'Real Estate Trust': string;
  '# of ST w/Prop': number;
  'Zestimate Total': string;
  'Zestimate Count': number;
  'LN Total': string;
  'LN Count': number;
  'SEC Stock Value': string;
  'SEC Stock or Insider': string;
  'Market Guide': string;
  'Market Guide Comp': string;
  'Market Guide Options': string;
  'Business Revenue': string;
  'Business Affiliation': string;
  'Pension Admin': string;
  'Pension Assets': string;
  'Estimated Capacity': string;
  'Annual Fund Likelihood': number;
  'Major Gift Likelihood': number;
  'PGID': number;
  'Vip Match': string;
  'Inner Circle': number;
  'Average Home Value': string;
  'Median Household Income': string;
  'Corp Tech': string;
  'FAA Pilots': string;
  'Airplane Owner': string;
  'Boat Owner': string;
  'Whos Who': string;
  'RFM Recent Gift': number;
  'RFM Freq': number;
  'RFM Money': number;
  'Classic Quality Score': number;
  'Prefix': string;
  'Suffix': string;
  'Higher Education Count': number;
  'Higher Education Total': string;
  'Education Gift Count': number;
  'Education Gift Amount': string;
  'Philanthropy and Grantmaking Count': number;
  'Philanthropy and Grantmaking Total': string;
  'Healthcare Count': number;
  'Healthcare Total': string;
  'Arts Gift Count': number;
  'Arts Gift Amount': string;
  'Republican Gift Count': number;
  'Republican Gift Total': string;
  'Democratic Gift Count': number;
  'Democratic Gift Amount': string;
  'Other Political Count': number;
  'Other Political Total': string;
  'Religion Count': number;
  'Religion Total': string;
  'Society Benefit Count': number;
  'Society Benefit Total': string;
  'Shale Wealth': number;
  'MBT Net Worth': string;
  'MBT Income Estimate': string;
  'MBT Highest Asset': string;
  'User1'?: string;
  'User2'?: string;
  'User3'?: string;
  'User4'?: string;
  'User5'?: string;
  'User6'?: string;
  'User7'?: string;
  'User8'?: string;
  'User9'?: string;
  'User10'?: string;
  'User11'?: string;
  'User12'?: string;
  'User13'?: string;
  'User14'?: string;
  'User15'?: string;
  'User16'?: string;
  'User17'?: string;
  'User18'?: string;
  'User19'?: string;
  'User20'?: string;
  'Email'?: string;
  'Assessed'?: string;
  'Assessment Questions'?: string;
  'IRS 990PF'?: string;
  'IRS PUB78'?: string;
}